export default {
    // fieldguide: {
    //     title: 'Website Development - A Field Guide to Newtown Creek',
    //     category: 'web',
    //     blurb: ' I built the front end site. A project by Rebecca Lieberman, Nick Hubbard, and Marina Zurkow.',
    //     imgsrc: 'projects/fieldguide/fieldguide.png',
    //     date: 'SPRING 2017',
    //     id: 'fieldguide',
    //     projectLink: 'https://hidden-forest-32016.herokuapp.com/',
    //     externalLink: true
    // },
    hundreddays: {
        title: '100 Days of Visualizing Algorithms',
        category: 'visual',
        blurb: 'An algorithm a day keeps the doctor away. Or something.',
        imgsrc: [
            'projects/hundreddays/insertion-sort-day3-small.gif',
            'projects/hundreddays/day42-poisson-disc.gif',
            'projects/hundreddays/day53-height-map-perspective.gif',
            'projects/hundreddays/day24-prim-mst-pathfinding.gif'
        ],
        date: 'ITP | SPRING 2017',
        id: 'hundreddays',
        projectLink: 'https://100daysofalgorithms.tumblr.com/',
        externalLink: true
    },
    pds: {
        title: 'Digital Prints',
        category: 'visual',
        blurb: 'A series of generative prints made in Rune.js',
        imgsrc: 'projects/pds/pds_thumb.png',
        date: 'ITP | FALL 2016',
        id: 'pds',
        projectLink: 'https://github.com/jcharry/programming-design-systems-projects',
    },
    sasscan: {
        title: "Sasscan",
        category: "physical",
        imgsrc: "projects/sasscan/sasscan_small.gif",
        blurb: "A trashcan that yells",
        date: "ITP | SPRING 2016",
        id: "sasscan",
        projectLink: "https://vimeo.com/164219386",
        credits: "Jamie Charry & Dana Abrassart"
    },
    tale: {
        title:"Tale of <user_defined_location>",
        category: "web",
        imgsrc: "projects/tale/tale1.png",
        blurb: "Algorithmic place-poem generator",
        date: "ITP | MAY 2016",
        id: "tale",
        projectLink:"http://tale.town",
        documentationLink: "http://itp.jcharry.com/2016/05/05/756/",
        credits: "Jamie Charry. MAY 2016",
    },
    ingredients: {
        title:"What's in my food?",
        category: "apps",
        imgsrc: "projects/ingredients/ingredients.gif",
        blurb: "iOS App - Ingredient Decoder",
        technologies: "Javascript, Phonegap/Cordova, OCR via Google Cloud Vision",
        desc: "Ever wonder what maltodextrin is and why its in your food? By simply taking a photo of an ingredients label, the user can explore what all those tricky ingredients are, where they come from, and why they're there in the first place.",
        date: "ITP | JUL 2016",
        id: "ingredients",
        projectLink:"https://vimeo.com/175415250",
        documentationLink: ["http://itp.jcharry.com/2016/03/07/whats-in-my-food-midterm-presentation/","http://itp.jcharry.com/2016/02/25/whats-in-my-food-pt-2-mockups/","http://itp.jcharry.com/2016/02/23/whats-in-my-food-pt-1/"],
        credits: "Jamie Charry. JUL 2016",
        longdesc:""
    },
    // brasslamp: {
    //     title: "Brass + Walnut Lamp",
    //     category: "physical",
    //     imgsrc: "projects/brasslamp/lamp_thumb.png",
    //     blurb: "Lathe + 4-axis milled lamp",
    //     date: "ITP | SPRING 2016",
    //     id: "brasslamp",
    //     projectLink: "http://itp.jcharry.com/2016/05/02/brass-walnut-and-cherry-lamp/",
    //     documentation: "http://itp.jcharry.com/2016/05/02/brass-walnut-and-cherry-lamp/"
    // },
    cocoa: {
        title:"An Interactive History of the Cocoa Bean",
        category: "web",
        imgsrc: "projects/cocoa/cocoa_thumb.png",
        blurb: "Web based slideshow",
        desc: "A slideshow style web page developed from scratch to educate folks about the humble cocoa bean. I wanted to try to implement simple transitions without leaning on libraries like jQuery for help.",
        technologies: "Vanilla Javascript, HTML, CSS",
        date: "ITP | FEB 2016",
        id: "cocoa",
        projectLink:"http://cocoa.jcharry.com",
        documentationLink: "",
        credits: "An ITP Project by Jamie Charry. Feb 2016",
        longdesc:""
    },
    // eafus: {
    //     title:"EAFUS Twitter Bot",
    //     category: "experiments",
    //     imgsrc: "projects/eafus/eafus_thumb.png",
    //     technologies: "Node, Javascript, Twitter API, text processing with Python",
    //     desc: "There are almost 4000 ingredients added to processed food. The FDA keeps a list of all these additives called EAFUS (Everything Added to Food in the United States). This bot tweets that list. Should take about 6 months to get through.",
    //     date: "ITP | FEB 2016",
    //     id: "eafus",
    //     projectLink:"https://twitter.com/EafusBot",
    //     documentationLink: "",
    //     credits: "Jamie Charry. Feb 2016",
    //     longdesc:""
    // },
    plasmicreflections: {
        title:"Plasmic Reflection",
        category: "physical",
        imgsrc: "projects/plasmicreflections/pr.gif",
        technologies: "Arduino, LED's, Heartbeat Sensor",
        blurb: "Your heartbeat, reflected. Editor's Choice Makerfaire NYC 2016!",
        desc: "A unique and personal experience, the Plasmic Reflection mirror encourages the user to fully inhabit their body and mind.  Developed over the course of several weeks at NYU ITP, the mirror acts as an extension of the user's heartbeat, allowing them to enter a meditative place where they are invited to look inward, or find silence.  Ultimately, the experience is up to the viewer.",
        date: "ITP | DEC 2015",
        id: "plasmicreflections",
        documentationLink:"http://itp.jcharry.com/2015/12/14/plasmic-reflections-final-documentation/",
        credits: "An ITP Project by Jamie Charry & Ella Dagan. Dec 2015",
        longdesc:""
    },
    // quppled: {
    //     title: "Quppled",
    //     category: "apps",
    //     imgsrc:"projects/quppled/quppled_thumb.png",
    //     blurb: "iOS app - Double Dating",
    //     technologies: "Swift",
    //     desc: "Very much in progress (but back burnered) Swift iOS app for meeting new couple friends.  Some might call it double dating.",
    //     date: "In Development, Started 2015",
    //     id:"quppled",
    //     projectLink:"https://player.vimeo.com/video/151353179",
    //     documentationLink: "https://github.com/jcharry/quppled",
    //     credits:""
    // },
    qad: {
        title: "Question a Day",
        category: "web",
        imgsrc: "projects/qad/qad_thumb.png",
        blurb: "Public Journal of Feelings",
        desc: "In today's facebook flooded internet world, we're often inundated with other people's feelings. Ultimately people are looking to connect with one. Question a Day is a simple attempt to allow for the sharing of deep feelings, semi-anonymously, to encourage us to look beyond our own feelings and to connect with those of a stranger.",
        technologies: "Javascript, Node, MongoDB, Sentiment analysis, p5.js",
        longdesc: "",
        date: "ITP | DEC 2015",
        src:"http://questionaday.herokuapp.com",
        id:"qad",
        projectLink:"http://questionaday.herokuapp.com/",
        documentationLink: "http://itp.jcharry.com/2015/12/01/public-question-a-day-final-documentation/",
        credits: ""
    },
    solarsynth: {
        title:"Solar Synthesizer",
        category: "experiments",
        imgsrc: "projects/solarsynth/solarsynth.gif",
        blurb: "Solar music",
        techologies: "p5.js",
        desc: "Clicking around draws lines. When planets cross those lines, they make music. Sound fun? Done entirely in p5.js",
        date: "ITP | OCT 2015",
        src:"http://itp.jcharry.com/solarSystem",
        id: "solarsynth",
        projectLink:"http://itp.jcharry.com/solarSystem/",
        documentationLink: "http://itp.jcharry.com/2015/10/01/solar-music/",
        credits: "By Jamie Charry"
    },
    colorflowers: {
        title:"HSB Drawings",
        category: "experiments",
        imgsrc: "projects/colorflowers/hsb_thumb.png",
        blurb: "A few algorithmic drawings",
        technologies: "p5.js",
        desc: "With only a few simple translations, rotations, loops, and a bit of randomization, it's quite amazing how many possible drawings can be created with just a few minor tweaks",
        date: "ITP | NOV 2015",
        id:"colorflowers",
        projectLink:"http://itp.jcharry.com/colorFlowers",
        documentationLink: "",
        credits: ""
    },
    artistcomp: {
        title:"Artist Comparator",
        category:"experiments",
        blurb: "Playing with the Echonest API",
        technologies: "p5.js, Echonest",
        imgsrc: "projects/artistcomp/artistcomp_thumb.png",
        thumbnail: "/images/artistcompsquare_thumb.png",
        desc: "Music can be quite difficult to quanity, but the folks at Echonest are trying. This p5 sketch averages several musical characteristics for the top 100 songs of each selected artist, and displays them for comparison",
        date: "ITP | NOV 2015",
        id:"artistcomp",
        projectLink:"http://itp.jcharry.com/artistComparator/",
        documentationLink: "",
        credits: ""
    }
    // particlesandwaves: {
    //     title:"Particles and Waves",
    //     category: "experiments",
    //     imgsrc: "projects/paw/particlesandwaves_thumb.png",
    //     blurb: "Canvas object interactions",
    //     technologies: "p5.js",
    //     desc: "A very early sketch to get a handle on object creation, interaction, and desctruction using p5 in the canvas.",
    //     date: "ITP | NOV 2015",
    //     id:"particlesandwaves",
    //     projectLink:"http://itp.jcharry.com/particlesAndWaves",
    //     documentationLink: "http://itp.jcharry.com/2015/09/16/particles-and-waves-icm-assignment-2/",
    //     credits: ""
    // }
};
